#### Import required libs

In [1]:
import sys
sys.path.append('/home/jupyter/app')

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from src.io_utils import load_dataframe

#### Define constants

In [2]:
GS_DIR_FEATURES = "gs://pcqm4mv2/data/features"
GS_DIR_AUTOML = "gs://pcqm4mv2/data/automl"

#### Load datasets

In [3]:
df_train = load_dataframe("train.csv", GS_DIR_FEATURES)

print("df_train shape:", df_train.shape)
df_train.head()

/opt/conda/lib/python3.7/site-packages/numpy/lib/arraysetops.py:580: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


df_train shape: (3378606, 29)


smiles  homolumogap  number_of_atoms  \
idx                                                                        
0    O=C1[N]c2ccncc2[CH][C@@H]1c1ccc(cc1)C     3.047675               30   
1            COc1cc(OC)ccc1/C=C/N(C(=O)C)C     4.410966               34   
2              C=CCN(C(=O)C)/C=C/c1ccccc1C     4.639541               33   
3              C=CCN(C(=O)C)/C=C/c1ccccc1F     4.492600               30   
4             C=CCN(C(=O)C)/C=C/c1ccccc1Cl     4.612330               30   

     number_of_heavy_atoms  number_of_bonds  number_of_heavy_bonds  \
idx                                                                  
0                       18               32                     20   
1                       17               34                     17   
2                       16               33                     16   
3                       16               30                     16   
4                       16               30                     16   

     number_of_conformations  exact_mol_weight  average_mol_weight  \
idx                                                                  
0                          0        236.094963             236.274   
1                          0        235.120843             235.283   
2                          0        215.131014             215.296   
3                          0        219.105942             219.259   
4                          0        235.076392             235.714   

     heavy_mol_weight  ...  number_of_B_atoms  number_of_C_atoms  \
idx                    ...                                         
0             224.178  ...                  0                 15   
1             218.147  ...                  0                 13   
2             198.160  ...                  0                 14   
3             205.147  ...                  0                 13   
4             221.602  ...                  0                 13   

     number_of_N_atoms  number_of_O_atoms  number_of_F_atoms  \
idx                                                            
0                    2                  1                  0   
1                    1                  3                  0   
2                    1                  1                  0   
3                    1                  1                  1   
4                    1                  1                  0   

     number_of_Si_atoms  number_of_P_atoms  number_of_S_atoms  \
idx                                                             
0                     0                  0                  0   
1                     0                  0                  0   
2                     0                  0                  0   
3                     0                  0                  0   
4                     0                  0                  0   

     number_of_Cl_atoms  number_of_Br_atoms  
idx                                          
0                     0                   0  
1                     0                   0  
2                     0                   0  
3                     0                   0  
4                     1                   0  

[5 rows x 29 columns]

In [4]:
df_val = load_dataframe("valid.csv", GS_DIR_FEATURES)

print("df_val shape:", df_val.shape)
df_val.head()

df_val shape: (73545, 29)


smiles  homolumogap  \
idx                                                               
3378606         COc1ccccc1N[C@H](/C(=N\C(=N)O)/O)C     4.587840   
3378607         COc1ccccc1N[C@H](/C(=N\C(=N)O)/O)C     4.971520   
3378613  CC(/N=C(\N/N=C/1\C[C@H]2[C@@H]1CC=C2)/S)C     5.496700   
3378614  CC(/N=C(\N/N=C/1\C[C@H]2[C@@H]1CC=C2)/S)C     5.485815   
3378624               C/N=C(\c1cc2c(s1)ccc(c2)F)/O     4.748387   

         number_of_atoms  number_of_heavy_atoms  number_of_bonds  \
idx                                                                
3378606               32                     17               32   
3378607               32                     17               32   
3378613               32                     15               33   
3378614               32                     15               33   
3378624               22                     14               23   

         number_of_heavy_bonds  number_of_conformations  exact_mol_weight  \
idx                                                                         
3378606                     17                        0        237.111341   
3378607                     17                        0        237.111341   
3378613                     16                        0        223.114319   
3378614                     16                        0        223.114319   
3378624                     15                        0        209.031063   

         average_mol_weight  heavy_mol_weight  ...  number_of_B_atoms  \
idx                                            ...                      
3378606             237.259           222.139  ...                  0   
3378607             237.259           222.139  ...                  0   
3378613             223.345           206.209  ...                  0   
3378614             223.345           206.209  ...                  0   
3378624             209.245           201.181  ...                  0   

         number_of_C_atoms  number_of_N_atoms  number_of_O_atoms  \
idx                                                                
3378606                 11                  3                  3   
3378607                 11                  3                  3   
3378613                 11                  3                  0   
3378614                 11                  3                  0   
3378624                 10                  1                  1   

         number_of_F_atoms  number_of_Si_atoms  number_of_P_atoms  \
idx                                                                 
3378606                  0                   0                  0   
3378607                  0                   0                  0   
3378613                  0                   0                  0   
3378614                  0                   0                  0   
3378624                  1                   0                  0   

         number_of_S_atoms  number_of_Cl_atoms  number_of_Br_atoms  
idx                                                                 
3378606                  0                   0                   0  
3378607                  0                   0                   0  
3378613                  1                   0                   0  
3378614                  1                   0                   0  
3378624                  1                   0                   0  

[5 rows x 29 columns]

#### Split `df_train` into `train` and `validate`

In [5]:
train_idx, validate_idx = train_test_split(df_train.index.values, test_size=0.025, random_state=2912)

In [6]:
train_idx

array([1263016, 2552159, 2855647, ..., 1592673, 2110379, 2975181])

In [7]:
validate_idx

array([1333351, 1971383, 1951760, ...,   61842, 3094930, 1387276])

#### Use `df_val` as `test`

In [8]:
test_idx = df_val.index.values
test_idx

array([3378606, 3378607, 3378613, ..., 3746602, 3746611, 3746612])

#### Concatenate `df_train` and `df_val` to a unique dataframe

In [9]:
df_unique = pd.concat([df_train, df_val])
df_unique

smiles  homolumogap  \
idx                                                                       
0                    O=C1[N]c2ccncc2[CH][C@@H]1c1ccc(cc1)C     3.047675   
1                            COc1cc(OC)ccc1/C=C/N(C(=O)C)C     4.410966   
2                              C=CCN(C(=O)C)/C=C/c1ccccc1C     4.639541   
3                              C=CCN(C(=O)C)/C=C/c1ccccc1F     4.492600   
4                             C=CCN(C(=O)C)/C=C/c1ccccc1Cl     4.612330   
...                                                    ...          ...   
3746593                             O=C/C=C/C=C(\C(=O)O)/N     3.733402   
3746601                            CC[C@](C(=O)O)(C(=O)C)O     5.991947   
3746602                               OC(=O)CCc1cccc(c1O)O     4.955193   
3746611                                             ClCCCl     8.179742   
3746612  O=CN(c1ccc(cc1)C(=O)N[C@H](C(=O)O)CCC(=O)O)C[C...     3.314347   

         number_of_atoms  number_of_heavy_atoms  number_of_bonds  \
idx                                                                
0                     30                     18               32   
1                     34                     17               34   
2                     33                     16               33   
3                     30                     16               30   
4                     30                     16               30   
...                  ...                    ...              ...   
3746593               17                     10               16   
3746601               20                     10               19   
3746602               23                     13               23   
3746611                8                      4                7   
3746612               57                     34               59   

         number_of_heavy_bonds  number_of_conformations  exact_mol_weight  \
idx                                                                         
0                           20                        0        236.094963   
1                           17                        0        235.120843   
2                           16                        0        215.131014   
3                           16                        0        219.105942   
4                           16                        0        235.076392   
...                        ...                      ...               ...   
3746593                      9                        0        141.042593   
3746601                      9                        0        146.057909   
3746602                     13                        0        182.057909   
3746611                      3                        0         97.969005   
3746612                     36                        0        473.165896   

         average_mol_weight  heavy_mol_weight  ...  number_of_B_atoms  \
idx                                            ...                      
0                   236.274           224.178  ...                  0   
1                   235.283           218.147  ...                  0   
2                   215.296           198.160  ...                  0   
3                   219.259           205.147  ...                  0   
4                   235.714           221.602  ...                  0   
...                     ...               ...  ...                ...   
3746593             141.126           134.070  ...                  0   
3746601             146.142           136.062  ...                  0   
3746602             182.175           172.095  ...                  0   
3746611              98.960            94.928  ...                  0   
3746612             473.446           450.262  ...                  0   

         number_of_C_atoms  number_of_N_atoms  number_of_O_atoms  \
idx                                                                
0                       15                  2                  1   
1                       13         

In [10]:
assert df_unique.shape[0] == len(df_train) + len(df_val)
assert df_unique.shape[1] == df_train.shape[1]
assert df_unique.shape[1] == df_val.shape[1]

#### Create `splitcol`

In [11]:
df_unique.loc[train_idx.tolist(), "splitcol"] = "TRAIN"
df_unique.loc[validate_idx.tolist(), "splitcol"] = "VALIDATE"
df_unique.loc[test_idx.tolist(), "splitcol"] = "TEST"

In [12]:
df_unique["splitcol"].value_counts(normalize=True)

TRAIN       0.954228
VALIDATE    0.024468
TEST        0.021304
Name: splitcol, dtype: float64

#### Save dataset to GCS

In [14]:
df_unique.to_csv(f"{GS_DIR_AUTOML}/train_val_test.csv")